version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:stable
    working_directory: /tmp


jobs:
  write-hello:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: "write hello world"
          command: echo "Hello World" > workspace/output.txt
      - persist_to_workspace:
          root: workspace
          paths:
            - output.txt
  say-hello:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Say hello"
          command: cat /tmp/workspace/output.txt
workflows:
  say-hello-workflow:
    jobs:
      - write-hello
      - say-hello:
          requires:
          - write-hello
