version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello"
  say-world:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say world"
          command: "echo World!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - say-world:
        requires: say-hello
